### ISSUE TITLE
Endpoints for LocalStateQuery via REST

### ISSUE THREAD

**Issue by musik-c** [blinklabs-io/cardano-node-api#25]
The LocalStateQuery Ouroboros protocol has many client endpoints.

- GetCurrentEra
- GetSystemStart
- GetChainBlockNo
- GetChainPoint
- GetEraHistory
- GetEpochNo
- GetCurrentProtocolParams
- GetGenesisConfig

This depends on blinklabs-io/gouroboros#315 for underlying support for the query communication with the Cardano Node.

**Comment by wolf31o2** [comment]
Merging ChainBlockNo, EpochNo, and ChainPoint into a single Tip to more closely match other tools and reduce the necessary API calls.

**Comment by wolf31o2** [comment]
The first part of this is in #134 and the second part will be in another pull request.

**Comment by wolf31o2** [comment]
The second part is in #143 with a caveat of a bug in gOuroboros around the Genesis Config.
