### ISSUE TITLE
Validating and testing the UTxORPC spec

### ISSUE THREAD

**Issue by musik-c** [blinklabs-io/cardano-node-api#27]

**Comment by wolf31o2** [comment]
Validation of the spec itself is an ongoing process as the specification is under development.

I validated against version 0.5.1 of the UTxO RPC spec, which is realized as generated code in the [go-codegen](https://github.com/utxorpc/go-codegen) repository. The generated code creates interfaces and types which must be completed and adhered to.

The Go compiler helps us out here tremendously, as it will refuse to compile an incomplete interface implementation.

Each module in UTxO RPC with user-operable functionality has been implemented.

- [x] Query
- [x] Submit
- [x] Sync
- [x] Watch

The next steps are to perform full data validation by crafting queries to run against Cardano Node API and to compare the results with expectations, which is covered by #34
