### ISSUE TITLE
Verifying and validating results against the spec

### ISSUE THREAD

**Issue by musik-c** [blinklabs-io/cardano-node-api#34]

**Comment by wolf31o2** [comment]
Issues generated:
- #208 
- #210

**Comment by verbotenj** [comment]
Addressed nil dereference
- https://github.com/blinklabs-io/gouroboros/pull/668

**Comment by verbotenj** [comment]
cardano-node:8.9.4
<https://github.com/utxorpc/go-sdk>
network: preprod

cardano-node-api:local (gouroborus:v0.90.0)
readParams()

Client logs:
Response: &{Msg:values:{cardano:{}}  ledger_tip:{slot:66443229  hash:"\xaa´\xb6\x88\xab\x86fQl\x99\x0c1-\x83\xaa\xa4\x01\xf9~\xd9\xca\xcc5׳\xa6ƀ\xb3\x96\x8b"} header:map[Content-Type:[application/grpc]

Expected empty response with ledger tip
(Specs weren't defined at the time of implementation)

**Comment by verbotenj** [comment]
# Test Query: `readUtxos`

### Environment

- **Cardano Node Version**: 8.9.4
- **Network**: Preprod
- **Test Deployment**: Cardano Node Api 0.2.0-Local (gouroborus:v0.90.0)
- **Test Code Repository**: https://github.com/utxorpc/go-sdk
- **Test Method**: readUtxos(ctx, client, "71a7498f086d378ec5e558581286629b678be1dd65d5d4e2a5d634ba6fdf8299")

### Client Logs

```logs
connecting to utxorpc host: <http://localhost:9090>
Ledger Tip:
  Slot: 66444229
  Hash: 4e5102a03983c905d02b103fbdf118b67f60b17fd452f44598ba508abf771f70
```

### Expect Output
N/A

**Comment by verbotenj** [comment]
# Test Query: `searchUtxos()`

### Environment

- **Cardano Node Version**: 8.9.4
- **Network**: Preprod
- **Test Deployment**: Cardano Node Api 0.2.0-Local (gouroborus:v0.90.0)
- **Test Code Repository**: https://github.com/utxorpc/go-sdk
- **Test Method**: searchUtxos(ctx, client, "101467bc3a356777b920d0c3f023198737e0e6f0ebe9cccabe18a4941316a4092303be48b6477c2a0593a8cd483ca045284585eb4853e84726")

### Client Logs

```logs
unknown
invalid character not part of charset: 98
[]
```

### Server Logs

```logs
Got a SearchUtxos request with predicate match:{cardano:{address:{exact_address:"\x10\x14g\xbc:5gw\xb9 \xd0\xc3\xf0#\x19\x877\xe0\xe6\xf0\xeb\xe9\xccʾ\x18\xa4\x94\x13\x16\xa4\t#\x03\xbeH\xb6G|*\x05\x93\xa8\xcdH<\xa0E(E\x85\xebHS\xe8G&"} asset:{}}}
```

### Expect Output
N/A

**Comment by verbotenj** [comment]
# Test Query: `submitTx()`

### Environment

- **Cardano Node Version**: 8.9.4
- **Network**: Preprod
- **Test Deployment**: Cardano Node Api 0.2.0-Local (gouroborus:v0.90.0)
- **Test Code Repository**: https://github.com/utxorpc/go-sdk
- **Test Method**: submitTx(ctx, client, "84a50081825820d3e1af74921ce5b4562ab13acab532af64e1cae02b4033153ab4490299ba478e01018282583900923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9568b72f85522e4a17d44a45cd021b9741b55d7cbc635c911625b015e1a00a7d8c082583900923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9568b72f85522e4a17d44a45cd021b9741b55d7cbc635c911625b015e1b00000001281aad84021a00029285031a03f6d57d0800a10081825820b829480e5d5827d2e1bd7c89176a5ca125c30812e54be7dbdf5c47c835a17f3d58409a97044722c96132d7bf446c8fb4f1ae95e52bfdc188d2a970695ce108eeda2ca7f5d196df4e79ab9bd1a33b0594c6c9138d2cdf65ea9f387ac03a948cdc9703f5f6")

### Client Logs

```logs
Connecting to utxorpc host: <http://localhost:9090>
Response: &{Msg:ref:"9U\xf9/\xb1\xce \x87\xfbz[@\xadg\x03\xec\xf5\xd5֊\xcc\xe1\xf7f\x8f\xc7O\x9d\xa33#\xd1" header:map[Content-Type:[application/grpc] Date:[Sun, 28 Jul 2024 15:32:34 GMT] Grpc-Accept-Encoding:[gzip] Grpc-Encoding:[gzip]] trailer:map[Grpc-Status:[0]]}
```


### Expect Output
Transaction reference; 
Got TXref: `3955f92fb1ce2087fb7a5b40ad6703ecf5d5dbccf7f7668fc74f9da33323d1`


---
**Unsigned Transaction**
**Test Method**: submitTx(ctx, client, "84a50081825820d3e1af74921ce5b4562ab13acab532af64e1cae02b4033153ab4490299ba478e01018282583900923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9568b72f85522e4a17d44a45cd021b9741b55d7cbc635c911625b015e1a00b71b0082583900923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9568b72f85522e4a17d44a45cd021b9741b55d7cbc635c911625b015e1b00000001280b6b44021a00029285031a03f6d2c00800a0f5f6")
### Client Logs

```logs
Connecting to utxorpc host: <http://localhost:9090>
unknown
[ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError ([UtxowFailure (GenericError ([0 [1 [923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9]]]))]))]
[]
panic: unknown: [ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError ([UtxowFailure (GenericError ([0 [1 [923d4b64e1d730a4baf3e6dc433a9686983940f458363f37aad7a1a9]]]))]))]
```

### Expect Output
N/A

**Comment by verbotenj** [comment]
# Test Query: `watchMempool()`

### Environment

- **Cardano Node Version**: 8.9.4
- **Network**: Preprod
- **Test Deployment**: Cardano Node Api 0.2.0-Local (gouroborus:v0.90.0)
- **Test Code Repository**: https://github.com/utxorpc/go-sdk
- **Test Method**: watchMempool(ctx, client) with (request with predicate <nil> and fieldMask <nil>)

### Client Logs
Waiting, no response
```
Connecting to utxorpc host: http://localhost:9090
```

### Server Logs

```logs
Got a WatchMempool request with predicate <nil> and fieldMask <nil>
```

### Expect Output
All transactions no filtering.
Got none.
